"""
Response formatting node.

Final node that ensures a proper response is ready for the user.
"""

import logging
from typing import Dict, Any
from langchain_core.messages import AIMessage

from backend.app.graph.state import AgentState

logger = logging.getLogger(__name__)


def format_response_node(state: AgentState) -> Dict[str, Any]:
    """
    Format the final response for the user.

    This node runs after subgraphs to ensure there's always
    a response ready. Some subgraphs may already set final_response.

    Args:
        state: Current agent state

    Returns:
        State update ensuring final_response is set
    """
    logger.info("=== FORMAT RESPONSE NODE ===")

    # If response already generated by subgraph, use it
    if state.get("final_response"):
        logger.info("Response already generated by subgraph")
        return {}

    # Check if we have errors
    errors = state.get("errors", [])
    if errors:
        error_msg = "I encountered some issues: " + "; ".join(errors)
        logger.info(f"Formatting error response: {error_msg}")
        return {
            "final_response": error_msg,
            "messages": [AIMessage(content=error_msg)]
        }

    # Fallback generic response
    fallback_msg = "I processed your request. How can I help you further?"
    logger.info("Using fallback response")

    return {
        "final_response": fallback_msg,
        "messages": [AIMessage(content=fallback_msg)]
    }
