"""
Agent state definition for LangGraph.

The AgentState is the core data structure that flows through all nodes in the graph.
It contains all context needed for the agent to make decisions and execute actions.

State Management:
- Each node receives the current state
- Nodes return partial state updates (not full state)
- LangGraph merges updates into the state
- State is immutable within a node
- Checkpointer persists state after each node execution
"""

from typing import TypedDict, List, Optional, Dict, Any, Annotated
from langchain_core.messages import BaseMessage
import operator


class AgentState(TypedDict):
    """
    Main state object for the ShopGraph AI agent.

    This state flows through all nodes and subgraphs in the execution graph.
    Each field serves a specific purpose in the agent's decision-making process.
    """

    # ===== Conversation Context =====
    messages: Annotated[List[BaseMessage], operator.add]
    """
    Full conversation history.
    Uses operator.add to append new messages rather than replacing.
    This is crucial for maintaining conversation context.
    """

    user_input: str
    """Current user message being processed."""

    thread_id: str
    """
    Unique identifier for this conversation thread.
    Used by checkpointer to isolate different conversations.
    """

    # ===== Intent and Routing =====
    intent: Optional[str]
    """
    Classified user intent. Possible values:
    - "search": User wants to find products
    - "compare": User wants to compare products
    - "order": User wants to place an order
    - "cart": User wants to manage cart
    - "chat": General conversation
    """

    route_to: Optional[str]
    """
    Routing decision - which node/subgraph to execute next.
    Determined by router nodes based on intent.
    """

    # ===== Search Context =====
    filters: Optional[Dict[str, Any]]
    """
    Extracted search filters from user input.
    Example: {
        "category": "laptop",
        "brand": "Apple",
        "max_price": 1500,
        "min_rating": 4.0
    }
    """

    products: Optional[List[Dict[str, Any]]]
    """
    Current search results.
    Persisted across conversation turns to enable refinement.
    Each product is a dict representation of the Product model.
    """

    # ===== Comparison Context =====
    selected_product_ids: List[str]
    """
    Product IDs selected for comparison or ordering.
    Example: ["prod_001", "prod_002", "prod_003"]
    """

    comparison_result: Optional[Dict[str, Any]]
    """
    Structured comparison data generated by comparison subgraph.
    Contains side-by-side feature comparison and LLM explanation.
    """

    # ===== Order Context =====
    selected_product: Optional[Dict[str, Any]]
    """
    Single product selected for ordering.
    Full product dict with all details.
    """

    cart_state: Optional[Dict[str, Any]]
    """
    Current cart state including items and total.
    """

    order_state: Optional[Dict[str, Any]]
    """
    Order confirmation details after successful order placement.
    """

    # ===== Error Handling =====
    errors: List[str]
    """
    Error messages accumulated during execution.
    Nodes can add errors without stopping execution.
    """

    # ===== Response Generation =====
    needs_response: bool
    """
    Flag indicating whether a response needs to be generated.
    Some nodes may set this to False if they handle response directly.
    """

    final_response: Optional[str]
    """
    Generated response text to be sent to the user.
    """


def create_initial_state(user_input: str, thread_id: str) -> AgentState:
    """
    Create initial state for a new user message.

    Args:
        user_input: User's message
        thread_id: Conversation thread identifier

    Returns:
        AgentState with initialized values
    """
    return AgentState(
        messages=[],
        user_input=user_input,
        thread_id=thread_id,
        intent=None,
        route_to=None,
        filters=None,
        products=None,
        selected_product_ids=[],
        comparison_result=None,
        selected_product=None,
        cart_state=None,
        order_state=None,
        errors=[],
        needs_response=True,
        final_response=None,
    )
